PROGS=1-1 1-2 1-3 1-4

all: ${PROGS}


1-1: 1-1.c
	gcc -o 1-1 1-1.c

1-2: 1-2.c
	gcc -g -o 1-2 1-2.c

1-3: 1-3.c
	gcc -g -o 1-3 1-3.c

1-4: 1-4.c
	gcc -o 1-4 1-4.c

zip:
	zip SethPalmerAssignment1.zip 1-1.c 1-2.c 1-3.c 1-4.c